#!/bin/bash

# This allows the admin to put the status as "warning" with a suitable
# message to indicate that the service is under test and should not
# be used by default.

# Define a variable GLITE_INFO_SERVICE_STATUS_XXX with a message string
# where XXX is the service name

if [ "$1" == "" ]; then
	exit
fi

eval SERVICE_STATUS=\$GLITE_INFO_SERVICE_STATUS_"$1"

if [ "$SERVICE_STATUS" == "" ]; then
	exit
else
	echo "$SERVICE_STATUS"
	exit 2
fi
